# Exploratory Data Analysis - Course Project 1
#### _Chris Vennes_
#### _August 22, 2015_

##Project Objectives
Get familar with R base ploting functionality by examining household energy usage over a 2 day period using data from the [UC Irvine Machine Learning Repository](http://archive.ics.uci.edu/ml/) using the "Individual household electric power consumption Data Set".  For descriptions of the data [see here](https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption).


##R Script Readmes
This GitHub contains R scripts for generating 4 graphs and a cooresponding png output from the script.  Each graph should have a width and a height of 480 pixels.  The R code should completely read the data create the graph and output to a png in the working folder.

##Loading the datasets
This assumes that there is a folder in the working directory called *exdata-data-household_power_consumption* containing the data named *household_power_consumption.txt* note this file is over 2M rows at a size of 126MB.  I am including the code for loading the dataset into each script as noted by the project objective but it would be better to load once and reuse the smaller dataset each time.  The code used for loading and cleaning the data is below:

```{r eval=FALSE}
  data <- read.table("./exdata-data-household_power_consumption/household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
  data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
  PlotData <- subset(data, Date>=as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
  PlotData$DateTime <- as.POSIXct(paste(PlotData$Date, PlotData$Time), format="%Y-%m-%d %H:%M:%S")
```